name: Rust

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src-tauri

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo build
        run: cargo build --verbose
